cathmart_products = [
    "Cardinal Health™ Self-Adherent Bandage, Lightweight, Non-Sterile",
    "Aluminum Two-Button Folding Walker",
    "Hollister Infyna Chic Female Intermittent Catheter",
    "Lansinoh Extra Pumping Set",
    "Bard Statlock Catheter Secure Foley Stabilization Device, Perspiration Holes",
    "CanDo® Overdoor Shoulder Pulley - Double Pulley with Door Bracket",
    "Curity Fabric Adhesive Bandages | Natural",
    "Pyridoxal-5-Phosphate",
    "Thermoskin Neck Wrap",
    "L-Glutamine - 500mg Tablets",
    "Drainable Fecal Collectors w/SoftFlex Skin Barrier by Hollister",
    "Unimom Zomee Z2 - Rechargeable Double Electric Breast Pump",
    "Prevail® Daily Underwear - Unisex",
    "Cardinal Health™ Hydrocolloid Dressing",
    "Dressing Stick With Foam Grip",
    "Compression Calf Sleeve CS6",
    "Elastic Shoe Lace With Cord-Lock",
    "4-Panel Abdominal Binders (1 Count)",
    "CanDo® Vinyl Coated Dumbbell - 3 lb - Green, pair",
    "Resveratrol Plus 200 mg",
    "Cervical Collars | Universal (1 Count)",
    "McKesson Baby Wipes, Soft Pack, Aloe / Vitamin E, Scented",
    "Thermoskin Premium Arthritis Gloves, Pair",
    "Freedom Belt Large Size",
    "Nelmed Urine Bag Calf Support",
    "Melatonin - 3 mg with Vitamin B-6",
    "Digestive Enzymes Vegetarian",
    "Huggies Little Snugglers, Baby Diaper, Size 2, Disposable",
    "Rusch Silicone Coated Latex Foley",
    "Compression Wrist Sleeve WS6",
    "Aluminum Transport Chair with Wheels | Various Colors (1 Count)",
    "Zomee Fit Wearable Breast Pump",
    "Kiinde Twist Starter Kit",
    "The ES6 Elbow Bracing Sleeve",
    "Manuka Honey Skin Barrier Protectant Cream",
    "CanDo® Foam Roller - Black Composite - Extra Firm - Round",
    "Bard Catheter Plugs and Protector Cap",
    "24\" Dressing Stick",
    "CorFit Sacroiliac Back Support Belt",
    "Hollister Extension Tubing 18\", With Connector",
    "Basic Rollators | Various Colors (1 Count)",
    "Pro-Stat® AWC Ready-to-Use Liquid Protein Supplement, Wild Cherry Punch, Sugar Free",
    "The Original Cuff® Ankle and Wrist Weight",
    "CanDo® Band Loop | Various Colors",
    "Unisex Adult Incontinence Brief McKesson Ultra Plus Bariatric 3X-Large Disposable Heavy Absorbency",
    "Flax Seed Oil - Lignan Rich / Unrefined Virgin Oil",
    "Kendall Versalon™ Non-Sterile Non-Woven Sponge, 4-Ply, Bulk, 4\" x 4\"",
    "Fabric Adhesive Bandages | Natural",
    "Nitrile Exam Gloves",
    "FS6 Compression Foot Sleeve",
    "WaxWel® Paraffin - 6 x 1-lb Blocks - Wintergreen Fragrance",
    "Adapt Lubricating Deodorant by Hollister, 1 Count",
    "Cane Replacement Tip, Black",
    "Thermoskin Sport Tennis Elbow Brace",
    "Cure Ultra Intermittent Male Catheter, Straight Tip",
    "DJO ProCare Open Patella Knee Sleeve",
    "Dry Disposable Washcloths, White",
    "Aluminum Shower Chair, With Back",
    "Sterile Saline Solution | 120 ML Cup",
    "Drop Arm Patient Commode",
    "Baseline® Measurement Tape, 60 inch",
    "Toilet Safety Rails",
    "Baby Diaper McKesson Tab Closure Size 6 Disposable",
    "Sterile Water Solution | 120 ML Cup",
    "CanDo® Digi-Flex® Hand Exercisers",
    "Incentive Spirometers Without 1-Way Valve, Adult",
    "Supreme Plastic Male Urinal, Clear with Splashproof Lid",
    "HR TruCath Night Drainage Bags",
    "TruCath Intermittent Catheter Insertion Kit",
    "PMI ProBasics™ Shower Chair, with Back",
    "Medical Tape McKesson White, Silk-Like Cloth, Non-Sterile",
    "Brava Elastic Ostomy Belt, 1 Count",
    "Circulation Thermal Slippers, Pair",
    "Povidone Iodine Prep Pad",
    "Bard Red Rubber Catheter, All-Purpose, 14Fr, 16\"",
    "FreeDerm Adhesive Remover",
    "Shoehorn, Flexible Plastic",
    "Bath Bench drive™ Padded Removable Arms Aluminum Frame With Backrest",
    "Reusable Hot/Cold Gel Pack 6\" x 9\"",
    "Chrome Finished Grab Bars",
    "Thermoskin Arthritic Knee Wrap",
    "D-Core Pillow | White",
    "Exam Table Paper (12 Count)",
    "ProStyle® Open Patella Knee Sleeve | Black (1 Count)",
    "Basic Comfort CorPak Hot & Cold Pack",
    "CanDo® Overdoor Shoulder Pulley - Single Pulley with Door Strap",
    "First Aid Only All-Purpose First Aid Kit 131 Pieces",
    "Thermoskin Adjustable Wrist / Hand Brace",
    "Cure Straight Tip Intermittent Catheter",
    "Aluminum Shower Chair, Without Back",
    "CanDo® Vinyl Coated Dumbbell - 4 lb - Light Blue, pair",
    "CanDo® Door (nub) Anchor with Webbing Loop for Band/Tubing (1 Count)",
    "FabLife™ Back Scrubber, 22 inch straight handle, 5 x 3 inch hourglass sponge",
    "ProBasics Three-in-One Folding Commode with Full Seat",
    "Elvie Stride",
    "Cure Catheter Insertion Kit, Cure K2",
    "CanDo® Vinyl Coated Dumbbell - 7 lb - Purple, pair",
    "Single-Tread Slippers BLUE LARGE (1 Count)",
    "Standard Instant Cold Packs",
    "Brownmed Seal-Tight Cast Protectors",
    "Kendall Dover™ 2-Way Silicone Elastomer-Coated Latex Foley Catheter 16\" 5cc Balloon Capacity",
    "Thermoskin Knee Support",
    "Bariatric Folding Walker with 5\" Wheels, 1 Count",
    "Freedom Belt Regular Size",
    "Thermoskin FXT Compression Socks, Calf",
    "Offset Handle Fashion Canes",
    "Incentive Spirometers, Adult, with One-Way Valve | 4000ML (1 Count)",
    "Carex Health Bed Pan 108 oz Regular",
    "Presto Ultimate Full Fit Briefs",
    "Push-Button Aluminum Crutches",
    "Breast Pumping Travel Bundle",
    "Dynarex Hydrocortisone Cream, 1 Count",
    "Thermoskin Sport Ankle Wrap",
    "Cure Extension Tube, Universal, for Intermittent Catheters, 29\"",
    "Ankle Bracing Sleeve - The AF7",
    "Seat Cushion McKesson 16 W X 16 D X 2 H Inch Foam / Gel",
    "Bard Leg Bag Extension Tubing with Connector 18\", Sterile, Latex-Free",
    "Cure Twist Intermittent Catheter",
    "Colles' Wrist Splint ProCare® Padded Aluminum/Foam",
    "3M Durapore™ Silk-Like Cloth Surgical Tape",
    "Arm Elevator Sling, One Size Fits Most",
    "Depend Guards for Men, Maximum Absorbency",
    "SpeediCath Intermittent Catheter Straight Tip, Male",
    "Huggies Little Movers Diapers, Jumbo Pack by Kimberly-Clark",
    "Medical Tape Curad® Water Resistant Silk-Like Cloth 1 Inch X 10 Yard White Non-Sterile",
    "BZK Antiseptic Towelettes, 100 Count",
    "Thermoskin Sacroiliac Belt",
    "Brava Strip Paste by Coloplast, 10 Count",
    "Baby Diaper McKesson Tab Closure Size 5 Disposable",
    "Convatec ActiveLife One-Piece Drainable Pouch with Cut-To-Fit Durahesive Plus® Skin Barrier, 10 Count",
    "CanDo® Handle with Adjustable Webbing for Band/Tubing (1 pair)",
    "Cimilre S6 Double Electric Breast Pump",
    "Compression Knee Sleeve KS7",
    "White Coated Steel Wall Grab Bars",
    "Bariatric Two-Button Folding Walker, 1 Count",
    "Sterile Bulb Irrigation Syringe Trays, 1 Count",
    "Extra-Wide Raised Toilet Seat, Aluminum Legs, 1 Count",
    "Bath Bench McKesson Without Arms Aluminum Frame Without Backrest 19-1/4 Inch Seat Width 300 lbs. Weight Capacity",
    "Cardinal Health™ Thin Hydrocolloid Dressing, 4\" x 4\"",
    "Thermoskin Sport Adjustable Thigh",
    "ProCare™ Briefs",
    "Kid's Chewable Multivitamin with Acidophilus",
    "Urinary Leg Bag with Anti-Reflux Valve – Sterile",
    "Nimbo Posterior Walker",
    "Bariatric Briefs, Size B",
    "Cure Ultra Intermittent Male Catheter, Coude Tip",
    "Wheelchair Drainage Bag Holders, 1 Count",
    "Sterile Piston Irrigation Syringe Trays",
    "WaxWel® Paraffin - 6 x 1-lb Blocks - Fragrance-Free",
    "Compression Patella Sleeve PS3",
    "Baby Buddha Double Electric Portable Breast Pump",
    "Breast Pump & Accessory Wipes Quick Clean™ Unscented",
    "Omega 3 Supplement Major® Fish Oil 500 mg Strength Softgel 130 per Bottle",
    "Unimom Zomee Z1 - Rechargeable Double Electric Breast Pump",
    "CanDo® Latex-Free Exercise Band - PEP™ Pack",
    "Triple Antibiotic Ointment",
    "Dover Extension Tubing 18\", With Latex Connector",
    "Huggies Little Snugglers, Baby Diaper, Size 1, Disposable",
    "Adult Forearm Crutches (Pair)",
    "CanDo® Pedal Exerciser - Preassembled",
    "Vitamin D3 1000 IU",
    "Heavy Duty Bariatric Footstool with Non-Skid Rubber Platform and Handrail",
    "Brava Moldable Rings by Coloplast",
    "Elvie Stride Plus",
    "Handheld Shower McKesson 84 Inch Hose",
    "Melatonin - 3 mg Sustained Release",
    "Accu-Therm Hot/Cold Gel Packs, 5x10",
    "Sterile Saline with Safety Seal, 100 mL",
    "TruCath Intermittent Catheter Insertion Kit with Drainage Bag",
    "Thermoskin Lumbar Support",
    "Men's Liberty External Catheter",
    "Medela Breast Milk Cooler Set",
    "Assura 1-Piece Urostomy Pouches w/Extended Wear Barrier by Coloplast, Transparent, 10 Count",
    "Dottie Tote",
    "Lansinoh Breastmilk Storage Bags",
    "Similac Powder Advanced Earlyshield Baby Formula",
    "Assura Standard Urostomy Pouches by Coloplast, Transparent, 10 Count",
    "DermaSeptin® Ointment",
    "Zinc Lozenges",
    "Saccharomyces Boulardii 250 mg",
    "Spectra Premium Accessory Kit",
    "Dynarex Vitamin A & D Ointment",
    "BodyMed Adult Washcloths",
    "Remedy Phytoplex Hydraguard",
    "Adapt Stoma Powder, 1 Count",
    "ACME United First Aid Only™ Bulk ANSI First Aid Kit, 110 Pieces",
    "FLIP-FLO Catheter Valves",
    "Relief Pak® HotSpot® Moist Heat Pack - standard size - 10\" x 12\"",
    "Thermoskin Sport Knee Stabilizer",
    "Hollister VaPro Plus Pocket No Touch Intermittent Female Catheter",
    "Children's Acidophilus / Grape Flavor",
    "CanDo® Vinyl Coated Dumbbell - 10 lb - Orange, pair",
    "Kendall Demacea™ Sterile Non-Woven Sponge 4-Ply, 4\" x 4\"",
    "Auto Squeeze Bottle Squeezer",
    "TruCath Silicone-Elastomer Coated Latex Foley Catheter, 2-Way, 5 mL Balloon",
    "Formed Sock Aid",
    "Cotton Clavicle Straps",
    "CanDo® Vinyl Coated Dumbbell - 1 lb - Pink, pair",
    "GF Health Lumex Uprise Onyx Folding Walker, 400 lb Weight Capacity, Aluminum",
    "Adapt Barrier Rings by Hollister",
    "CanDo® Digi-Extend® Hand Exerciser - exerciser with 16 bands (4 each: tan, yellow, red, green)",
    "Incentive Spirometers, Adult | 2500ML (1 Count)",
    "IV Stand Floor Stand McKesson 2-Hook 5-Legs, Dual-Wheel Nylon Casters, Cast Aluminum Base",
    "McKesson Urinary Drain Bags Anti-Reflux Valve",
    "Presto Supreme Full Fit Briefs",
    "Dynarex Bacitracin Zinc Ointment",
    "Basic Knee Walker, 1 Count",
    "Catheter Plugs/Protector Cap | Multiple Quantities",
    "Compression Elbow Sleeve ES3",
    "ESTEEM Extended Cuff Powder-Free, Nitrile Exam Gloves, 12\", Non-Sterile",
    "Sure Care™ Extra Protective Underwear",
    "Abdominal Binder",
    "Bath Bench McKesson Removable Arms Plastic Frame Removable Backrest",
    "FS4 Plantar Fasciitis Sock",
    "Addipak Sterile Saline Solution",
    "CanDo® Theraputty® Exercise Material | 2oz",
    "7-Day Classic Pill Planner, 2XL",
    "Fast Freeze Cold Therapy Pain Relief Gel",
    "Thermoskin Ankle Wrap",
    "Thermoskin Arthritis Gloves, Full Finger",
    "Relief Pak® English Ice Cap Reusable Ice Bag - 9\" Diameter",
    "Baby Diaper McKesson Tab Closure Size 7 Disposable",
    "Commode Replacement Tips",
    "Synthetic Fur Lined Heel Protectors, Pair",
    "Relief Pak® HotSpot® Moist Heat Pack - Neck Contour - 9\" x 24\"",
    "Thermoskin Sport Ankle Brace",
    "Dressing Change Tray McKesson Central Line",
    "Underpads 30 x 36, 10 Count",
    "Huggies Little Snugglers, Baby Diaper, Newborn, Disposable",
    "Surgilube Surgical Lubricant by Sandoz",
    "Nice'n Clean® Baby Wipes by PDI, Inc",
    "Thermoskin Open Knee Wrap Stabilizer",
    "Avant Gauze Non-Woven Sterile Sponges",
    "Foot & Calf Compression Sleeve FS6+",
    "Core Wheelchair",
    "Fingertip Pulse Oximeter, Deluxe (2 AAA Batteries Included)",
    "Attends Bariatric Underwear",
    "CanDo® Gel Squeeze Ball - Standard Circular",
    "Cleansing Towelettes, 100 Count",
    "Medela Breast Pump Accessory Starter Kit",
    "Shoehorn, Metal 24\"",
    "Beneprotein Instant Protein Unflavored Powder",
    "Self Wipe Toilet Aid",
    "TruCath™ Premium Flocked Back Leg Bag with Flip Valve",
    "DynaFoam AG Bordered Silver Foam Dressing",
    "Coloplast Gentle Rain® Extra Mild Shampoo and Skin Cleanser 4 oz",
    "Unimom Minuet & Opera Breast Shield Kit - Double Set",
    "Chrome Quad Cane Large Base",
    "Ameda Store'N Pour Breast Milk Storage Bags",
    "Vinyl Exam Gloves",
    "WaxWel® Paraffin - 6 x 1-lb Bags of Pastilles - Fragrance-Free",
    "Autodrop Eye Drop Guide",
    "CanDo® Vinyl Coated Dumbbell - 6 lb - Red, pair",
    "McKesson Stirrup Ankle Brace with Air and Gel Bladders",
    "Non-Sterile Tongue Depressors",
    "Prevail Breezers Briefs",
    "Bariatric Quad Canes",
    "MicroBeads Moist Heat Pack (5\" x 12\")",
    "Ameda Mya Hospital Strength Rechargeable Double Electric Breast Pump with Large Tote & Extra Accessories",
    "Aluminum Quad Cane Small Base",
    "CoolXChange",
    "Remedy Basics Moisturizing Body Lotion (1 Count)",
    "CanDo® SoftGrip® Hand Weights",
    "SoClean 2 CPAP Cleaner and Sanitizer",
    "Bard Statlock Foley Stabilization Device, Tricot Anchor Pad",
    "Folding Fixed Arms Steel Commode",
    "Compression Socks 3M™ Futuro™ Knee High Medium Black Closed Toe",
    "Medela Freestyle Hands-Free Breast Pump",
    "Hot / Cold Pack McKesson General Purpose Large 6-3/4 X 10-1/2 Inch Gel Reusable",
    "Nitrile Select Exam Gloves",
    "Unisex Overnight Underwear",
    "CanDo® Vinyl Coated Dumbbell - 2 lb - Violet, pair",
    "Unisex Adult Absorbent Underwear McKesson Ultra Pull On with Tear Away Seams",
    "CanDo® Overdoor Shoulder Pulley - Single Pulley with Door Bracket",
    "CanDo® Foam Roller - White PE Foam",
    "Baby Diaper McKesson Tab Closure Size 4 Disposable",
    "ARDO Calypso-To-Go | Double Electric Breast Pump On The Go",
    "Andover Moleskin 4 yds L x 9\" W, Tan",
    "3-in-1 Steel Commode",
    "Gel Foam Pressure Redistribution Cushions",
    "Cure Ultra Intermittent Female Catheter, Straight Tip",
    "Seat Cushion Elements 16 W X 16 D X 3 H Inch Foam / Gel",
    "Adult Bariatric Crutches",
    "Padded Bariatric Drop-Arm Commode",
    "Cardinal Health™ Cath Secure® Plus Foley Catheter Securement Device",
    "CanDo® Foam Roller - Blue PE Foam - 6\" x 36\" - Round",
    "BARDEX® I.C. Infection Control Foley Catheters",
    "Medela Quick Clean Micro Steam Bags",
    "Aluminum Adjustable Height Cane",
    "Wings™ Plus Adult Briefs",
    "DS6 Decompression Foot Sleeve, Single Sleeve",
    "CanDo® Inflatable Exercise Ball",
    "Drive Medical Deluxe Handheld Shower Spray with Diverter Valve",
    "Heavy Duty Wheelchair",
    "Tennis Elbow Support",
    "Single-Tread Slippers BEIGE X-LARGE (1 Count)",
    "Sterile Water Solution | 100ML",
    "SpeediCath Flex Coude Tip Pro Intermittent Catheter",
    "Crutch Accessory Kit, Gray, 1 Count",
    "CanDo® Vinyl Coated Dumbbell - 5 lb - Blue, pair",
    "ProBasics Bariatric Transfer Bench, 500 lb. Weight Capacity",
    "Aura Jumper Fingertip Pulse Oximeter",
    "Bard Leg Bag Extension Tubing with Connector, Non-Sterile, Latex Free, 18\"",
    "American Diagnostic Adtemp™ Digital Sheaths For 60-Second Digital Thermometer, Disposable",
    "Infant Heel Warmers",
    "Knocked Down Bath Transfer Bench Removable Arm Rail 17-1/2 to 22-1/2 Inch Seat Height 400 lbs. Weight Capacity",
    "Hollister VaPro Plus Pocket No Touch Intermittent Male Catheter",
    "Aluminum Transfer Bench",
    "Face Down Pillow",
    "Cure Catheter Insertion Kit, Cure K1",
    "Shampoo & Body Wash from McKesson",
    "ARDO Alyssa Double Electric Breast Pump",
    "Medical Nutrition USA Pro-Stat® Sugar Free 64 Ready-to-Use Liquid Protein Supplement 30 oz",
    "Brava Elastic Barrier Strips, 20 Count",
    "Cure Hydrophilic Pediatric Catheters",
    "Ankle Brace with Figure 8 Ossur® FormFit Lace-Up Ankle Splints",
    "Povidone Iodine Prep Swabsticks",
    "Basic Specimen Containers",
    "Medela Tender Care Hydrogel Pads",
    "Thermoskin FXT Compression Socks, Ankle",
    "All-Terrain Knee Walker",
    "Thermoskin Knee Patella Support",
    "Relief Pak® ColdSpot™ Blue Vinyl Pack - Standard - 11\" x 14\"",
    "Urethral Catheterization Trays with 14Fr Vinyl Urethral Catheter",
    "Bard I.C. Infection Control Urine Drainage Bag with Anti-Reflux Chamber, 2000mL",
    "Thermoskin Plantar FXT",
    "CanDo® Balance Disc - 14\" (35 cm) Diameter - Blue",
    "Tranquility SlimLine Disposable Brief",
    "CanDo® Theraputty® Exercise Material - 4 oz",
    "Pontoon Bedpan McKesson Graphite 2 Quart / 1893 mL",
    "Diaper Rash Treatment Boudreaux's Butt Paste, Scented Ointment",
    "Cure Ultra Plus Intermittent Female Catheter, Straight Tip",
    "Kent Precision Foods Group Thick-It® Original Instant Food & Beverage Thickener, 36 oz",
    "Pampers Sensitive Baby Wipes, Unscented",
    "Alternating Pressure Pads | ADJUSTABLE (1 Count)",
    "Sterile Non-Stick Pads",
    "Sure Care™ Plus Protective Underwear",
    "Thermoskin Adjustable Sports Shoulder",
    "FabLife™ Hip Kit",
    "TruCath Closed System Catheter Kits",
    "CanDo® Exercise Band | 6 Yards | Latex Free",
    "ConvaTec ActiveLife® One-Piece Drainable Pouch, 3/4\" to 2-1/2\" Cut-To-Fit, 12\" L, Transparent",
    "McKesson Baby Wipes, Soft Pack, Aloe / Vitamin E, Unscented",
    "Sterile Abdominal Pads",
    "Moxie GT Gait Trainer",
    "Standard Bariatric Rollator, 1 Count",
    "CanDo® Theraputty® Exercise Material - 1 lb",
    "Cardinal Health™ Hydrocolloid Wound Dressing, 6\" x 6\"",
    "Kids Adhesive Bandages",
    "SafeWash Sterile Saline Wound Wash, 7.4 oz",
    "Molnlycke Mepiform® Safetac Self-Adherent Soft Silicone Dressing 2\" x 3\", Thin, Flexible",
    "McKesson 7/8\" Cane / Crutch Tip",
    "Cardinal Health™ Premium Flocked Back Leg Bag with Flip Valve",
    "Attends Care Briefs",
    "Key Handle Tube Squeezer",
    "Thermoskin Elbow Wrap",
    "3M Coban Self-Adherent Wrap, Lightweight, Latex-Free, Non-Sterile, Tan",
    "CanDo® Exercise Tubing-with-Handles | 48\"",
    "Performance Quad Sleeve – The QS4",
    "Lofric Elle Intermittent Catheter",
    "Elastic Shoe Laces",
    "Rusch EasyTap Leg Bag",
    "ProBasics Deluxe Height Adjustable Aluminum Rollator, 8\" Wheels, 300 lb Capacity, 13.75\" Seat, Burgundy",
    "Padded Transfer Bench with Non-Skid Feet",
    "Disposable Fitted Stretcher Sheets | Blue",
    "Dispoz-a-Bag, Bard Urinary Leg Bag with Flip-Flo Valve, Large 32 oz, Fabric Straps",
    "Adapt Barrier Pastes by Hollister, 1 Count",
    "5-MTHF 1 mg",
    "Vitamin B-12",
    "Vitamin D-3 drops / 2,000 IU",
    "Vitamin C 500mg / Orange Chewable",
    "Vitamin C 1000 mg with Bioflavonoid Complex",
    "Active Life Nutrient Capsules",
    "Marine Fish Oils",
    "Buffered Vitamin C",
    "L-Theanine",
    "Vitamin B-6",
    "DHEA 25 mg",
    "DHEA 50 mg",
    "Vitamin A, D3 & K2",
    "Acetyl-L-Carnitine / 750 mg",
    "Magnesium 400 mg",
    "Ubiquinol - 30 count",
    "L-Arginine 500 mg",
    "Vitamin K2",
    "Ginkgo Biloba / 120 mg - 50 count",
    "Pantothenic Acid"
]